name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Show PR Info
        run: echo "Pull Request Triggered!"

      - name: Show Commit Message
        run: git log -1 --pretty=%B

      - name: Run Script
        run: bash scripts/system_info.sh